# TAKE HOME LAB EXERCISE - 01

-----------

**(1). The value Range(0,10) ,  convert the list to `2D array`.**

In [4]:
import numpy as np

a = [i for i in range(0,10)]
print(a)
a1 = np.array(a).reshape(2,5)
print(a1)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


-------------------------------------------------------------

**(2).Print or show only 3 decimal places of the numpy array `random_arr`**

In [87]:
random_arr = np.random.rand(3,3).round(3)
print(random_arr)

[[0.727 0.541 0.131]
 [0.414 0.779 0.584]
 [0.183 0.826 0.105]]


----------------------------------

**(3).The number of items printed to be limit in python numpy array a to a maximum of 6 elements.**

   
     Intake : x = np.arange(15)
               array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
               
     Result : ([ 0,  1,  2, ..., 12, 13, 14])

In [101]:
np.set_printoptions(threshold=10)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

---------------------

**(4). An arrays of `x` and `y` , Stack the `x` and `y` arrays Horizontal.**


    Intake:
                x = np.arange(10).reshape(2,-1)

                y = np.repeat(1, 10).reshape(2,-1)

 
    
    Result:       ([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
                   [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [13]:
x = np.arange(10).reshape(2,-1)
print(x)
y = np.repeat(1,10).reshape(2,-1)
print(y)
n1 = np.hstack((x,y))
n1

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

----------------------

**(5). There are two array `x` and `y` ,output to be the matching items in both the array.**
    
    
    Intake: 
   
        x = np.array([1,2,3,2,3,4,3,4,5,6])
        y = np.array([7,2,10,2,7,4,9,4,9,8])
 
    Results:
        
         ([2, 4])
            
    

In [96]:
x = np.array([1,2,3,2,3,4,3,4,5,6])
y = np.array([7,2,10,2,7,4,9,4,9,8])
# print(x)
# print(y)
# n1 = x[x==y]
# n1
# n2 = np.array(list(set(n1)))
# n2

np.array(list(set(x[np.in1d(x,y)])))

array([2, 4])

---------------------

**(6). There are two array x and y ,drop the items in `X` which already exist in `Y`.**

   
    INTAKE:
     x = np.array([1,2,3,4,5])
     y = np.array([5,6,7,8,9])
    
    
    RESULT:
     ([1,2,3,4])
        
    

In [71]:
List = []
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])
for i in x:
    if i in y:
        break
    else:
        List.append(i)
z = np.array(List)
z

array([1, 2, 3, 4])

--------------------------

**(7). Reverse the rows of a 2D array.**


    Intake : X = np.arange(9).reshape(3,3)
    
    Result :      ([[6, 7, 8],
                    [3, 4, 5],
                    [0, 1, 2]])

In [52]:
x = np.arange(9).reshape(3,3)
print(x)
y = x[::-1]
print()
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[6 7 8]
 [3 4 5]
 [0 1 2]]


----------------------

**(8). Reverse the columns of a 2D array.**

    Intake : X = np.arange(9).reshape(3,3)
    
    Result :     ([[2, 1, 0],
                   [5, 4, 3],
                   [8, 7, 6]])


In [53]:
x = np.arange(9).reshape(3,3)
print(x)
y = x[:,::-1]
print()
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[2 1 0]
 [5 4 3]
 [8 7 6]]


---------------------

**(9). Print the ranks for the given numeric array `x`.**
 
   
    Intake:
    np.random.seed(10)
    x = np.random.randint(20, size=10)
    print(x)
    [ 9  4 15  0 17 16 17  8  9  0]
    
    
    Result:
    [4 2 6 0 8 7 9 3 5 1]
    

In [81]:
np.random.seed(10)
x = np.random.randint(20,size=10)
print(x)
temp = x.argsort()
print(temp)
ranks1 = temp.argsort()
print()
print(ranks1)


[ 9  4 15  0 17 16 17  8  9  0]
[3 9 1 7 0 8 2 5 4 6]

[4 2 6 0 8 7 9 3 5 1]


--------------------

**(10). Print a rank array of the same shape as a given numeric array `x`.**


    Intake:
    np.random.seed(10)
    x = np.random.randint(20, size=[2,5])
    print(a)
    [[ 9  4 15  0 17]
    [16 17  8  9  0]]
    
    Result:
    [[4 2 6 0 8]
    [7 9 3 5 1]]

In [85]:
np.random.seed(10)
x = np.random.randint(20, size=[2,5])
print(x)
print()
print(np.argsort(np.argsort(x.reshape(1,10))).reshape(2,5))

[[ 9  4 15  0 17]
 [16 17  8  9  0]]

[[4 2 6 0 8]
 [7 9 3 5 1]]


--------------------------------

**(11). Subtract the 1d array y_1d from the 2d array x_2d, such that each item of y_1d subtracts from respective row of x_2d.**
    
    Intake:
    x_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
    y_1d = np.array([1,2,3])
    
    Result:
     [[2 2 2]
     [2 2 2]
     [2 2 2]]

In [80]:
x_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
y_1d = np.array([1,2,3])
y1d = y_1d.reshape(3,1)

z_2d = x_2d - y1d
print(z_2d)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


----------------

# ----------------------------------HAPPY LEARNING--------------------------------------------------

-------------------